name = input("What is your name? ")
age = int(input("How old are you? "))
adress = input("Which city do you live in? ")
print("=======USER PROFILE=======")
print("Name:", name)
print("Age:", age)
print("City:", adress)
print("Next year age:", age + 1)
print("===========================")
